Repository superwerker/superwerker, pull requests merged in 2021-05, with the labels that each got.

#214 Feedbackchange
  README.md
Labels: ready

#213 Add more visible buttons for installation paths
  README.md
Labels: ready

#209 refactor: enable script to be used to delete single accounts
  tests/close-active-subaccounts/close-account.js
  tests/close-active-subaccounts/close-active-subaccounts.js
  tests/close-active-subaccounts/lib/index.js
Labels: ready

#206 feat: rename SCP from "ServiceControlPolicy" into "superwerker"
  templates/service-control-policies.yaml
Labels: testing

#221 ci: empty commit to trigger codebuild
  DEVELOPMENT.md
  tests/build.yaml
  tests/start-build.sh
Labels: wontfix
